### ISSUE TITLE
Update to v0.1.0-beta.14

### ISSUE THREAD

**Issue by Sheyla1996** [darkfoxdeveloper/flarum-ext-spanish#11]
Can you add support for beta 14?

**Comment by meugeniatr** [comment]
I am using this extension in Flarum beta 14 but translation for moments are not working :( 

Is it possible to make it work for this version soon? 

Thanks !

**Comment by darkfoxdeveloper** [comment]
Sorry for the delay in answering, I'll look at it as soon as I can.

**Comment by darkfoxdeveloper** [comment]
Solved.
