### ISSUE TITLE
Update to v0.1.0-beta.9

### ISSUE THREAD

**Issue by jslirola** [darkfoxdeveloper/flarum-ext-spanish#2]
Check _core_ files in original [english package](https://github.com/flarum/lang-english/releases/tag/v0.1.0-beta.9) and update with necessary changes.

**Comment by darkfoxdeveloper** [comment]
I Update Soon

**Comment by jslirola** [comment]
Okay, if you want add me as reviewer in the related PR.

**Comment by darkfoxdeveloper** [comment]
@jslirola Can test the new version compatible with beta9? Thanks
