### ISSUE TITLE
Update to v0.1.0-beta.13

### ISSUE THREAD

**Issue by jslirola** [darkfoxdeveloper/flarum-ext-spanish#5]
Compare with original files and update to beta 13.

Repository: https://github.com/flarum/lang-english/tree/v0.1.0-beta.13/locale

@darkfoxdeveloper Do you remember what's the purpose of the JS files in "formal" and "informal" folders? E.g:

https://github.com/darkfoxdeveloper/flarum-ext-spanish/blob/master/locale/formal/config.js

**Comment by darkfoxdeveloper** [comment]
It is an old feature where it was sought to have a more urban or formal language, to be able to change between the two, it will be eliminated when updating to next version
